# Generated by Django 6.0.7 on 2026-08-04 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Scanning'), ('done', 'Finished'), ('failed', 'Failed'), ('unavailable', 'Share unavailable'), ('aborted', 'Stopped for safety')], default='queued', max_length=12)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('dry_run', models.BooleanField(default=False)),
                ('scanned', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('vanished', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('bytes_seen', models.BigIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('problems', models.JSONField(blank=True, default=list, help_text='First few unreadable paths.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='fs_modified_at',
            field=models.DateTimeField(blank=True, help_text='mtime as reported by the share.', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='missing_since',
            field=models.DateTimeField(blank=True, help_text='Set when a scan no longer finds the file.', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='origin',
            field=models.CharField(choices=[('managed', 'Created here'), ('scanned', 'Found on a share')], default='managed', max_length=8),
        ),
        migrations.AddField(
            model_name='node',
            name='rel_path',
            field=models.CharField(blank=True, help_text='POSIX path within the share.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('create_folder', 'Created folder'), ('upload', 'Added files'), ('rename', 'Renamed'), ('move', 'Moved'), ('copy', 'Copied'), ('trash', 'Moved to trash'), ('restore', 'Restored'), ('purge', 'Deleted permanently'), ('star', 'Starred'), ('unstar', 'Unstarred'), ('download', 'Downloaded'), ('import', 'Imported from share'), ('vanished', 'Gone from share'), ('undo', 'Undid an operation')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScanRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120, unique=True)),
                ('mount_path', models.CharField(help_text='Absolute path of the mounted share.', max_length=1024)),
                ('enabled', models.BooleanField(default=True)),
                ('read_only', models.BooleanField(default=True, help_text='Refuse rename/move/delete on files catalogued from this share.')),
                ('require_mount', models.BooleanField(default=True, help_text='Abort unless mount_path is a real mount point.')),
                ('max_missing_ratio', models.FloatField(default=0.25, help_text='Abort the missing-file pass if a larger share of the catalogue vanished at once.')),
                ('follow_symlinks', models.BooleanField(default=False)),
                ('max_depth', models.PositiveSmallIntegerField(default=0, help_text='0 means unlimited.')),
                ('min_size', models.BigIntegerField(default=0, help_text='Skip files smaller than this.')),
                ('exclude', models.JSONField(blank=True, default=list, help_text='fnmatch patterns matched against each entry name.')),
                ('missing_policy', models.CharField(choices=[('flag', 'Flag as missing'), ('trash', 'Move to trash'), ('delete', 'Remove from the catalogue')], default='flag', max_length=6)),
                ('batch_size', models.PositiveIntegerField(default=500, help_text='Entries per transaction. Keeps write locks short on long scans.')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(help_text='Folder in the tree this share is mirrored into.', on_delete=django.db.models.deletion.CASCADE, related_name='scan_roots', to='explorer.node')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='scan_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='explorer.scanroot'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['scan_root', 'rel_path'], name='node_share_path_idx'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('scan_root__isnull', False)), fields=('scan_root', 'rel_path'), name='node_unique_path_per_share'),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_runs', to='explorer.operation'),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='scan_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='explorer.scanroot'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['scan_root', '-started_at'], name='scanrun_recent_idx'),
        ),
    ]
