"""Tests for the transcode app.

Where ffmpeg is available these run against real, tiny clips generated by
lavfi — a stubbed subprocess would prove nothing about argument construction,
which is exactly the part most likely to be wrong.
"""

import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from django.core.files.base import ContentFile
from django.test import TestCase, override_settings
from django.urls import reverse

from explorer.models import Node, Operation, ScanRoot

from . import ffmpeg, services
from .models import MediaProbe, Preset, TranscodeJob

HAS_FFMPEG = shutil.which("ffmpeg") and shutil.which("ffprobe")
requires_ffmpeg = unittest.skipUnless(HAS_FFMPEG, "ffmpeg is not installed")


def make_clip(path: Path, seconds: int = 1, size: str = "320x240") -> Path:
    """A real, tiny video file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-nostdin", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", f"testsrc=size={size}:rate=15:duration={seconds}",
            "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}",
            "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-shortest", str(path),
        ],
        check=True,
        capture_output=True,
    )
    return path


class TranscodeTestCase(TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.base = Path(self.tmp.name)

        self.media_root = self.base / "media"
        self.work_dir = self.base / "work"
        self.share_dir = self.base / "share"
        self.share_dir.mkdir(parents=True, exist_ok=True)

        overrides = override_settings(
            MEDIA_ROOT=str(self.media_root),
            TRANSCODE={
                **self.settings_transcode(),
                "WORK_DIR": str(self.work_dir),
            },
        )
        overrides.enable()
        self.addCleanup(overrides.disable)

        self.root = Node.objects.create(name="My Drive", kind=Node.Kind.FOLDER)
        self.folder = Node.objects.create(parent=self.root, name="Footage", kind=Node.Kind.FOLDER)
        self.preset = Preset.objects.get(slug="proxy-480p")

    def settings_transcode(self):
        from django.conf import settings

        return dict(settings.TRANSCODE)

    def add_local_file(self, name="clip.mp4", parent=None, seconds=1):
        """A node whose bytes live in MEDIA_ROOT, like a browser upload."""
        source = make_clip(self.base / "src" / name, seconds=seconds)
        node = Node(parent=parent or self.folder, name=name, kind=Node.Kind.FILE)
        node.upload.save(name, ContentFile(source.read_bytes()), save=False)
        node.size = node.upload.size
        node.save()
        return node


# --------------------------------------------------------------------------- #
#  Argument construction — no ffmpeg needed
# --------------------------------------------------------------------------- #
class PresetTests(TestCase):
    def test_default_presets_are_installed(self):
        self.assertTrue(Preset.objects.filter(slug="web-1080p", enabled=True).exists())
        self.assertEqual(Preset.objects.count(), 7)

    def test_output_name_uses_suffix_and_container(self):
        preset = Preset.objects.get(slug="web-720p")
        self.assertEqual(preset.output_name("Beach Day.MOV"), "Beach Day-720p.mp4")

    def test_audio_preset_drops_video(self):
        preset = Preset.objects.get(slug="audio-m4a")
        args = ffmpeg.build_args(preset, "/in.mov", "/out.m4a")
        self.assertIn("-vn", args)
        self.assertIn("libmp3lame" if preset.slug == "audio-mp3" else "aac", args)

    def test_scale_filter_escapes_its_comma(self):
        preset = Preset.objects.get(slug="web-720p")
        args = ffmpeg.build_args(preset, "/in.mov", "/out.mp4")
        self.assertIn("scale=-2:min(ih\\,720)", args)

    def test_remux_preset_copies_streams_without_quality_flags(self):
        args = ffmpeg.build_args(Preset.objects.get(slug="remux-mp4"), "/in.mkv", "/out.mp4")
        self.assertEqual(args[args.index("-c:v") + 1], "copy")
        self.assertNotIn("-crf", args)

    def test_filenames_are_never_shell_interpreted(self):
        preset = Preset.objects.get(slug="web-720p")
        nasty = "/tmp/a b; rm -rf $HOME/'quote'.mov"
        args = ffmpeg.build_args(preset, nasty, "/out.mp4")
        self.assertIn(nasty, args)  # one argv element, not a shell string

    def test_preset_rejecting_both_streams(self):
        from django.core.exceptions import ValidationError

        preset = Preset(slug="x", label="X", video_codec="none", audio_codec="none")
        with self.assertRaises(ValidationError):
            preset.clean()

    def test_extra_args_must_be_strings(self):
        from django.core.exceptions import ValidationError

        with self.assertRaises(ValidationError):
            Preset(slug="y", label="Y", extra_args=[{"nope": 1}]).clean()

    def test_parse_frame_rate(self):
        self.assertEqual(ffmpeg.parse_rate("30000/1001"), 29.97)
        self.assertEqual(ffmpeg.parse_rate("25/1"), 25.0)
        self.assertEqual(ffmpeg.parse_rate("0/0"), 0.0)
        self.assertEqual(ffmpeg.parse_rate(None), 0.0)


# --------------------------------------------------------------------------- #
#  Eligibility and destination rules
# --------------------------------------------------------------------------- #
class QueueingTests(TranscodeTestCase):
    def test_only_media_files_are_eligible(self):
        video = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        doc = Node.objects.create(parent=self.folder, name="a.pdf", size=10)
        self.assertTrue(services.is_media(video))
        self.assertFalse(services.is_media(doc))
        self.assertFalse(services.is_media(self.folder))

    def test_folders_expand_to_the_media_inside(self):
        Node.objects.create(parent=self.folder, name="a.mov", size=10)
        Node.objects.create(parent=self.folder, name="notes.txt", size=10)
        nested = Node.objects.create(parent=self.folder, name="Day 2", kind=Node.Kind.FOLDER)
        Node.objects.create(parent=nested, name="b.mp4", size=10)

        found = services.expand([self.folder])

        self.assertEqual({n.name for n in found}, {"a.mov", "b.mp4"})

    def test_the_same_conversion_cannot_be_queued_twice(self):
        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        first = services.queue(nodes=[node], preset=self.preset)
        second = services.queue(nodes=[node], preset=self.preset)
        self.assertEqual(len(first["queued"]), 1)
        self.assertEqual(second["duplicate"], 1)
        self.assertEqual(TranscodeJob.objects.count(), 1)

    def test_a_different_preset_can_be_queued(self):
        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        services.queue(nodes=[node], preset=self.preset)
        report = services.queue(nodes=[node], preset=Preset.objects.get(slug="web-720p"))
        self.assertEqual(len(report["queued"]), 1)

    def test_output_of_a_local_file_goes_beside_it(self):
        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        self.assertEqual(services.output_folder(node), self.folder)

    def test_output_of_a_read_only_share_file_goes_to_a_managed_folder(self):
        share_folder = Node.objects.create(parent=self.root, name="Share", kind=Node.Kind.FOLDER)
        share = ScanRoot.objects.create(
            label="Share", mount_path=str(self.share_dir), node=share_folder, read_only=True
        )
        share_folder.scan_root = share
        share_folder.origin = Node.Origin.SCANNED
        share_folder.rel_path = "sub"
        share_folder.save()
        node = Node.objects.create(
            parent=share_folder, name="a.mov", size=10,
            origin=Node.Origin.SCANNED, scan_root=share, rel_path="sub/a.mov",
        )

        destination = services.output_folder(node)

        self.assertNotEqual(destination, share_folder)
        self.assertEqual(destination.name, "Transcodes")
        self.assertIsNone(destination.scan_root_id)

    def test_share_file_at_the_mirror_root_also_goes_to_transcodes(self):
        """The mirror folder must keep matching the share, so nothing is filed into it."""
        mirror = Node.objects.create(parent=self.root, name="Media share", kind=Node.Kind.FOLDER)
        share = ScanRoot.objects.create(
            label="Media", mount_path=str(self.share_dir), node=mirror, read_only=True
        )
        node = Node.objects.create(
            parent=mirror, name="a.mov", size=10,
            origin=Node.Origin.SCANNED, scan_root=share, rel_path="a.mov",
        )

        self.assertEqual(services.output_folder(node).name, "Transcodes")

    def test_writable_share_files_keep_their_output_alongside(self):
        mirror = Node.objects.create(parent=self.root, name="Scratch share", kind=Node.Kind.FOLDER)
        share = ScanRoot.objects.create(
            label="Scratch", mount_path=str(self.share_dir), node=mirror, read_only=False
        )
        node = Node.objects.create(
            parent=mirror, name="a.mov", size=10,
            origin=Node.Origin.SCANNED, scan_root=share, rel_path="a.mov",
        )

        self.assertEqual(services.output_folder(node), mirror)

    def test_cancelling_a_queued_job(self):
        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        services.cancel(job)
        job.refresh_from_db()
        self.assertEqual(job.status, TranscodeJob.Status.CANCELLED)

    def test_claim_is_exclusive(self):
        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        self.assertIsNotNone(services.claim(str(job.pk)))
        self.assertIsNone(services.claim(str(job.pk)))  # a second worker gets nothing

    def test_sweep_fails_abandoned_jobs(self):
        from django.utils import timezone

        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        TranscodeJob.objects.filter(pk=job.pk).update(
            status=TranscodeJob.Status.RUNNING,
            started_at=timezone.now() - timezone.timedelta(hours=9),
        )
        self.assertEqual(services.sweep_stuck(minutes=180), 1)
        self.assertEqual(TranscodeJob.objects.get(pk=job.pk).status, TranscodeJob.Status.FAILED)

    def test_missing_file_fails_the_job_with_a_readable_error(self):
        node = Node.objects.create(parent=self.folder, name="ghost.mov", size=10)
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        job = services.run(services.claim(str(job.pk)))
        self.assertEqual(job.status, TranscodeJob.Status.FAILED)
        self.assertIn("no file on disk", job.error)


# --------------------------------------------------------------------------- #
#  The real thing
# --------------------------------------------------------------------------- #
@requires_ffmpeg
class RunTests(TranscodeTestCase):
    def test_probe_reads_real_metadata(self):
        node = self.add_local_file(seconds=1)
        probe = services.probe_node(node)
        self.assertEqual(probe.error, "")
        self.assertAlmostEqual(probe.duration_seconds, 1.0, delta=0.4)
        self.assertEqual((probe.width, probe.height), (320, 240))
        self.assertEqual(probe.video_codec, "h264")
        self.assertEqual(probe.audio_codec, "aac")

    def test_transcode_produces_a_playable_smaller_file(self):
        node = self.add_local_file(seconds=2)
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]

        job = services.run(services.claim(str(job.pk)))

        self.assertEqual(job.status, TranscodeJob.Status.DONE, job.error)
        self.assertEqual(job.progress, 100)
        self.assertIsNotNone(job.output)

        output = job.output
        self.assertEqual(output.name, "clip-proxy.mp4")
        self.assertEqual(output.parent, self.folder)
        self.assertTrue(Path(output.upload.path).exists())
        self.assertEqual(output.size, Path(output.upload.path).stat().st_size)

        # It's a real video, downscaled as the preset asked.
        result = ffmpeg.probe(output.upload.path)
        self.assertEqual(result.height, 240)  # source was smaller; never upscales
        self.assertTrue(result.has_video and result.has_audio)

    def test_source_is_left_alone(self):
        node = self.add_local_file()
        before = Path(node.upload.path).read_bytes()
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        services.run(services.claim(str(job.pk)))
        self.assertEqual(Path(node.upload.path).read_bytes(), before)
        self.assertTrue(Node.objects.filter(pk=node.pk).exists())

    def test_conversion_is_written_to_the_audit_log(self):
        node = self.add_local_file()
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        job = services.run(services.claim(str(job.pk)))

        operation = Operation.objects.get(kind=Operation.Kind.TRANSCODE)
        self.assertEqual(operation.status, Operation.Status.DONE)
        self.assertEqual(operation.items.get().node, job.output)
        self.assertFalse(operation.can_undo)
        self.assertEqual(operation.detail["preset"], "proxy-480p")

    def test_work_directory_is_left_clean(self):
        node = self.add_local_file()
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        services.run(services.claim(str(job.pk)))
        leftovers = list(self.work_dir.glob("job-*"))
        self.assertEqual(leftovers, [])

    def test_audio_extraction(self):
        node = self.add_local_file(seconds=1)
        preset = Preset.objects.get(slug="audio-m4a")
        job = services.queue(nodes=[node], preset=preset)["queued"][0]

        job = services.run(services.claim(str(job.pk)))

        self.assertEqual(job.status, TranscodeJob.Status.DONE, job.error)
        result = ffmpeg.probe(job.output.upload.path)
        self.assertFalse(result.has_video)
        self.assertTrue(result.has_audio)

    def test_a_non_media_file_fails_rather_than_producing_junk(self):
        node = Node(parent=self.folder, name="notes.mp4", kind=Node.Kind.FILE)
        node.upload.save("notes.mp4", ContentFile(b"this is not a video"), save=False)
        node.size = node.upload.size
        node.save()

        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        job = services.run(services.claim(str(job.pk)))

        self.assertEqual(job.status, TranscodeJob.Status.FAILED)
        self.assertIn("ffprobe", job.error)
        self.assertIsNone(job.output)

    def test_cancellation_stops_a_running_job(self):
        """Cancel is checked mid-run, so a long encode stops promptly."""
        node = self.add_local_file(seconds=60)
        slow = Preset.objects.create(
            slug="slow-test", label="Slow", container="mp4",
            video_codec="libx264", crf=18, speed="veryslow", audio_codec="aac",
        )
        job = services.queue(nodes=[node], preset=slow)["queued"][0]
        TranscodeJob.objects.filter(pk=job.pk).update(cancel_requested=True)

        job = services.run(services.claim(str(job.pk)))

        self.assertEqual(job.status, TranscodeJob.Status.CANCELLED)
        self.assertIsNone(job.output)
        self.assertEqual(list(self.work_dir.glob("job-*")), [])

    def test_timeout_stops_a_runaway_encode(self):
        node = self.add_local_file(seconds=30)
        slow = Preset.objects.create(
            slug="slow-timeout", label="Slow", container="mp4",
            video_codec="libx265", crf=18, speed="veryslow", audio_codec="aac",
        )
        job = services.queue(nodes=[node], preset=slow)["queued"][0]

        with override_settings(TRANSCODE={**self.settings_transcode(),
                                          "WORK_DIR": str(self.work_dir),
                                          "MAX_JOB_SECONDS": 1}):
            job = services.run(services.claim(str(job.pk)))

        self.assertEqual(job.status, TranscodeJob.Status.FAILED)
        self.assertIn("limit", job.error)

    def test_task_entrypoint(self):
        from .tasks import run_transcode, transcode_nodes

        node = self.add_local_file()
        result = transcode_nodes.enqueue([str(node.pk)], "proxy-480p")
        self.assertEqual(result.return_value["queued"], 1)
        job = TranscodeJob.objects.get()
        self.assertEqual(job.status, TranscodeJob.Status.DONE, job.error)

        # Redelivery of the same task must not run it twice.
        again = run_transcode.enqueue(str(job.pk))
        self.assertFalse(again.return_value["claimed"])
        self.assertEqual(TranscodeJob.objects.count(), 1)

    def test_probe_pending_task(self):
        from .tasks import probe_pending

        self.add_local_file("a.mp4")
        Node.objects.create(parent=self.folder, name="b.pdf", size=5)
        self.assertEqual(probe_pending.enqueue().return_value, 1)
        self.assertEqual(MediaProbe.objects.count(), 1)


# --------------------------------------------------------------------------- #
#  Views
# --------------------------------------------------------------------------- #
class ViewTests(TranscodeTestCase):
    def test_choose_lists_presets_and_counts_eligible_files(self):
        video = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        doc = Node.objects.create(parent=self.folder, name="a.pdf", size=10)

        response = self.client.get(
            reverse("transcode:choose"), {"ids": [str(video.pk), str(doc.pk)]}
        )

        self.assertContains(response, "Editing proxy 480p")
        self.assertContains(response, "1 media file")

    def test_choose_with_nothing_convertible(self):
        doc = Node.objects.create(parent=self.folder, name="a.pdf", size=10)
        response = self.client.get(reverse("transcode:choose"), {"ids": [str(doc.pk)]})
        self.assertContains(response, "Nothing in that selection")

    @requires_ffmpeg
    def test_start_queues_and_reports(self):
        node = self.add_local_file()
        response = self.client.post(
            reverse("transcode:start"), {"ids": [str(node.pk)], "preset": "proxy-480p"}
        )
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Queued 1 file")
        self.assertContains(response, "hx-swap-oob")  # the toast
        self.assertEqual(TranscodeJob.objects.count(), 1)

    def test_start_with_no_media_says_so(self):
        doc = Node.objects.create(parent=self.folder, name="a.pdf", size=10)
        response = self.client.post(
            reverse("transcode:start"), {"ids": [str(doc.pk)], "preset": "proxy-480p"}
        )
        self.assertContains(response, "No media files")
        self.assertEqual(TranscodeJob.objects.count(), 0)

    def test_panel_renders(self):
        self.assertEqual(self.client.get(reverse("transcode:panel")).status_code, 200)

    def test_cancel_view(self):
        node = Node.objects.create(parent=self.folder, name="a.mov", size=10)
        job = services.queue(nodes=[node], preset=self.preset)["queued"][0]
        response = self.client.post(reverse("transcode:cancel", args=[job.pk]))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(TranscodeJob.objects.get(pk=job.pk).status, TranscodeJob.Status.CANCELLED)

    def test_explorer_offers_the_convert_action(self):
        response = self.client.get(reverse("explorer:index"))
        self.assertContains(response, reverse("transcode:choose"))
