# Generated by Django 6.1 on 2026-09-09 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("explorer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "media_kind",
                    models.CharField(
                        choices=[("video", "Video"), ("audio", "Audio")],
                        default="video",
                        max_length=5,
                    ),
                ),
                (
                    "container",
                    models.CharField(
                        default="mp4", help_text="Output extension.", max_length=10
                    ),
                ),
                (
                    "video_codec",
                    models.CharField(
                        default="libx264",
                        help_text="Codec name, 'copy' to remux, or 'none' to drop the video stream.",
                        max_length=20,
                    ),
                ),
                (
                    "crf",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Quality; lower is better.", null=True
                    ),
                ),
                (
                    "speed",
                    models.CharField(
                        blank=True,
                        help_text="x264/x265 -preset, e.g. veryfast.",
                        max_length=12,
                    ),
                ),
                (
                    "max_height",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Downscale to this height. Never upscales.",
                        null=True,
                    ),
                ),
                ("fps_cap", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("audio_codec", models.CharField(default="aac", max_length=20)),
                (
                    "audio_bitrate",
                    models.CharField(blank=True, default="128k", max_length=10),
                ),
                (
                    "hardware_accel",
                    models.CharField(
                        blank=True,
                        help_text="ffmpeg -hwaccel value, e.g. vaapi. Leave blank for CPU.",
                        max_length=20,
                    ),
                ),
                (
                    "threads",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0 lets ffmpeg decide. Set a low number to stay polite.",
                        null=True,
                    ),
                ),
                ("extra_args", models.JSONField(blank=True, default=list)),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Appended to the file stem.",
                        max_length=30,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "label"],
            },
        ),
        migrations.CreateModel(
            name="MediaProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_seconds", models.FloatField(default=0)),
                ("container", models.CharField(blank=True, max_length=30)),
                ("video_codec", models.CharField(blank=True, max_length=30)),
                ("audio_codec", models.CharField(blank=True, max_length=30)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("fps", models.FloatField(default=0)),
                ("bitrate", models.BigIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=250)),
                ("probed_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="explorer.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscodeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Converting"),
                            ("done", "Finished"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=9,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("source_bytes", models.BigIntegerField(default=0)),
                ("output_bytes", models.BigIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0)),
                ("elapsed_seconds", models.FloatField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "log",
                    models.TextField(blank=True, help_text="Tail of ffmpeg's stderr."),
                ),
                ("command", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        help_text="Folder the result is filed into.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcode_targets",
                        to="explorer.node",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcode_jobs",
                        to="explorer.operation",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcoded_from",
                        to="explorer.node",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="transcode.preset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcode_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcode_jobs",
                        to="explorer.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="job_status_recent_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=("source", "preset"),
                        name="transcode_one_active_job_per_source_preset",
                    )
                ],
            },
        ),
    ]
