# Generated by Django 6.1 on 2026-09-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("enabled", models.BooleanField(default=True)),
                ("graph", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TranscodeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "video_codec",
                    models.CharField(
                        choices=[
                            ("h264", "H.264 / AVC"),
                            ("hevc", "H.265 / HEVC"),
                            ("av1", "AV1"),
                            ("vp9", "VP9"),
                            ("mpeg2video", "MPEG-2"),
                            ("other", "Other"),
                        ],
                        default="hevc",
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.CharField(
                        choices=[("mkv", "MKV"), ("mp4", "MP4")],
                        default="mkv",
                        max_length=10,
                    ),
                ),
                ("audio_codec", models.CharField(default="copy", max_length=20)),
                (
                    "quality",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="CRF for CPU encoders, CQ/global_quality for hardware.",
                    ),
                ),
                ("preset", models.CharField(default="medium", max_length=20)),
                (
                    "hw_accel",
                    models.CharField(
                        choices=[
                            ("none", "CPU only"),
                            ("nvenc", "NVIDIA NVENC"),
                            ("qsv", "Intel QuickSync"),
                            ("vaapi", "VAAPI"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "max_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Downscale anything taller. Blank keeps the source height.",
                        null=True,
                    ),
                ),
                (
                    "max_bitrate_kbps",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Flag files above this bitrate even if the codec matches.",
                        null=True,
                    ),
                ),
                (
                    "extra_args",
                    models.CharField(
                        blank=True,
                        help_text="Appended verbatim to the ffmpeg command.",
                        max_length=400,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("hostname", models.CharField(blank=True, max_length=200)),
                ("concurrency", models.PositiveSmallIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("jobs_completed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("probe", "Probe"),
                            ("transcode", "Transcode"),
                            ("flow", "Flow"),
                            ("scan", "Scan"),
                        ],
                        default="transcode",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("cancelling", "Cancelling"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "task_result_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("progress", models.FloatField(default=0.0)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("eta_seconds", models.IntegerField(blank=True, null=True)),
                ("size_before", models.BigIntegerField(default=0)),
                ("size_after", models.BigIntegerField(default=0)),
                (
                    "trace",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nodes visited, in order, with the output taken.",
                    ),
                ),
                ("command", models.TextField(blank=True)),
                ("log", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="pipeline.flow",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="files.library",
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="files.mediafile",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="pipeline.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "-priority", "created_at"],
                        name="pipeline_jo_state_06fa63_idx",
                    )
                ],
            },
        ),
    ]
