# Generated by Django 6.1 on 2026-08-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "path",
                    models.CharField(
                        help_text="Absolute path the worker can read.", max_length=500
                    ),
                ),
                (
                    "extensions",
                    models.CharField(
                        default="mkv,mp4,avi,mov,m4v,ts,wmv",
                        help_text="Comma separated, no dots.",
                        max_length=200,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("scan_interval_minutes", models.PositiveIntegerField(default=720)),
                (
                    "auto_queue",
                    models.BooleanField(
                        default=True,
                        help_text="Queue a transcode as soon as a file fails the profile check.",
                    ),
                ),
                ("last_scan_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_scan_finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "libraries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TranscodeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "video_codec",
                    models.CharField(
                        choices=[
                            ("h264", "H.264 / AVC"),
                            ("hevc", "H.265 / HEVC"),
                            ("av1", "AV1"),
                            ("vp9", "VP9"),
                            ("mpeg2video", "MPEG-2"),
                            ("other", "Other"),
                        ],
                        default="hevc",
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.CharField(
                        choices=[("mkv", "MKV"), ("mp4", "MP4")],
                        default="mkv",
                        max_length=10,
                    ),
                ),
                ("audio_codec", models.CharField(default="copy", max_length=20)),
                (
                    "quality",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="CRF for CPU encoders, CQ/global_quality for hardware.",
                    ),
                ),
                ("preset", models.CharField(default="medium", max_length=20)),
                (
                    "hw_accel",
                    models.CharField(
                        choices=[
                            ("none", "CPU only"),
                            ("nvenc", "NVIDIA NVENC"),
                            ("qsv", "Intel QuickSync"),
                            ("vaapi", "VAAPI"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "max_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Downscale anything taller. Blank keeps the source height.",
                        null=True,
                    ),
                ),
                (
                    "max_bitrate_kbps",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Flag files above this bitrate even if the codec matches.",
                        null=True,
                    ),
                ),
                (
                    "extra_args",
                    models.CharField(
                        blank=True,
                        help_text="Appended verbatim to the ffmpeg command.",
                        max_length=400,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("hostname", models.CharField(blank=True, max_length=200)),
                ("concurrency", models.PositiveSmallIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("jobs_completed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1000, unique=True)),
                ("rel_path", models.CharField(max_length=1000)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "original_size_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Size before this pipeline first touched the file.",
                    ),
                ),
                ("mtime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Not scanned"),
                            ("probing", "Reading metadata"),
                            ("ready", "Meets target"),
                            ("queued", "Queued"),
                            ("transcoding", "Transcoding"),
                            ("transcoded", "Transcoded"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("missing", "File missing"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("unknown", "Not evaluated"),
                            ("meets_target", "Meets target"),
                            ("needs_transcode", "Needs transcode"),
                            ("unreadable", "Unreadable"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("verdict_reason", models.CharField(blank=True, max_length=300)),
                ("container", models.CharField(blank=True, max_length=20)),
                ("video_codec", models.CharField(blank=True, max_length=30)),
                ("audio_codec", models.CharField(blank=True, max_length=30)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("bitrate_kbps", models.PositiveIntegerField(blank=True, null=True)),
                ("last_probed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="pipeline.library",
                    ),
                ),
            ],
            options={
                "ordering": ["rel_path"],
            },
        ),
        migrations.AddField(
            model_name="library",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="libraries",
                to="pipeline.transcodeprofile",
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("probe", "Probe"),
                            ("transcode", "Transcode"),
                            ("scan", "Scan"),
                        ],
                        default="transcode",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("cancelling", "Cancelling"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "task_result_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("progress", models.FloatField(default=0.0)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("eta_seconds", models.IntegerField(blank=True, null=True)),
                ("size_before", models.BigIntegerField(default=0)),
                ("size_after", models.BigIntegerField(default=0)),
                ("command", models.TextField(blank=True)),
                ("log", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="pipeline.library",
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="pipeline.mediafile",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="pipeline.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["library", "status"], name="pipeline_me_library_e62fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["verdict"], name="pipeline_me_verdict_cfee87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["-updated_at"], name="pipeline_me_updated_304632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["state", "-priority", "created_at"],
                name="pipeline_jo_state_06fa63_idx",
            ),
        ),
    ]
