# Generated by Django 6.1 on 2026-08-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('graph', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='trace',
            field=models.JSONField(blank=True, default=list, help_text='Nodes visited, in order, with the output taken.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('probe', 'Probe'), ('transcode', 'Transcode'), ('flow', 'Flow'), ('scan', 'Scan')], default='transcode', max_length=20),
        ),
        migrations.AlterField(
            model_name='library',
            name='profile',
            field=models.ForeignKey(help_text='Used when no flow is set, and as the fallback for simple setups.', on_delete=django.db.models.deletion.PROTECT, related_name='libraries', to='pipeline.transcodeprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='pipeline.flow'),
        ),
        migrations.AddField(
            model_name='library',
            name='flow',
            field=models.ForeignKey(blank=True, help_text='A flow takes precedence over the profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libraries', to='pipeline.flow'),
        ),
    ]
