# Generated by Django 6.1 on 2026-09-02 15:59

import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_add_flows"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="meta",
            field=models.JSONField(blank=True, default=pipeline.models.def_meta),
        ),
    ]
