# Generated by Django 6.1 on 2026-09-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_mediafile_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="audio_codec",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="bitrate_kbps",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="container",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="video_codec",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="width",
        ),
    ]
