# Generated by Django 6.1 on 2026-09-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_remove_mediafile_audio_codec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="video_codec",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
