# Generated by Django 6.1 on 2026-09-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
