# Generated by Django 6.1 on 2026-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("offer_id", models.CharField(db_index=True, max_length=100)),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("has_video_assets", models.BooleanField(default=False)),
                (
                    "environment",
                    models.CharField(
                        choices=[("production", "Production"), ("staging", "Staging")],
                        default="production",
                        max_length=20,
                    ),
                ),
                ("processing_datetime", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("processing", "Processing"),
                            ("error", "Error"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-processing_datetime"],
            },
        ),
    ]
