# Generated by Django 6.1 on 2026-09-09 19:23

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "path",
                    models.CharField(
                        help_text="Absolute path the worker can read.", max_length=500
                    ),
                ),
                (
                    "extensions",
                    models.CharField(
                        default="mkv,mp4,avi,mov,m4v,ts,wmv",
                        help_text="Comma separated, no dots.",
                        max_length=200,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("scan_interval_minutes", models.PositiveIntegerField(default=720)),
                (
                    "auto_queue",
                    models.BooleanField(
                        default=True,
                        help_text="Queue a transcode as soon as a file fails the profile check.",
                    ),
                ),
                ("last_scan_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_scan_finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "libraries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1000, unique=True)),
                ("rel_path", models.CharField(max_length=1000)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "original_size_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Size before this pipeline first touched the file.",
                    ),
                ),
                ("mtime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Not scanned"),
                            ("probing", "Reading metadata"),
                            ("ready", "Meets target"),
                            ("queued", "Queued"),
                            ("transcoding", "Transcoding"),
                            ("transcoded", "Transcoded"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("missing", "File missing"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("unknown", "Not evaluated"),
                            ("meets_target", "Meets target"),
                            ("needs_transcode", "Needs transcode"),
                            ("unreadable", "Unreadable"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("verdict_reason", models.CharField(blank=True, max_length=300)),
                ("video_codec", models.CharField(blank=True, max_length=30)),
                ("last_probed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(blank=True, default=files.models.def_meta)),
            ],
            options={
                "ordering": ["rel_path"],
            },
        ),
    ]
