# Generated by Django 6.1 on 2026-09-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="A flow takes precedence over the profile.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="libraries",
                to="pipeline.flow",
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="profile",
            field=models.ForeignKey(
                help_text="Used when no flow is set, and as the fallback for simple setups.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="libraries",
                to="pipeline.transcodeprofile",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="files.library",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["library", "status"], name="files_media_library_2fcefb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["verdict"], name="files_media_verdict_f714ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["-updated_at"], name="files_media_updated_39e725_idx"
            ),
        ),
    ]
