# Generated by Django 6.0.7 on 2026-08-04 12:38

import django.db.models.deletion
import django.db.models.functions.text
import explorer.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("folder", "Folder"), ("file", "File")],
                        default="file",
                        max_length=6,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        default=0, help_text="Bytes. Always 0 for folders."
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=120)),
                (
                    "upload",
                    models.FileField(
                        blank=True, null=True, upload_to=explorer.models.upload_to
                    ),
                ),
                ("starred", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "path",
                    models.CharField(
                        db_index=True, default="", editable=False, max_length=1024
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="explorer.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-kind", django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("create_folder", "Created folder"),
                            ("upload", "Added files"),
                            ("rename", "Renamed"),
                            ("move", "Moved"),
                            ("copy", "Copied"),
                            ("trash", "Moved to trash"),
                            ("restore", "Restored"),
                            ("purge", "Deleted permanently"),
                            ("star", "Starred"),
                            ("unstar", "Unstarred"),
                            ("download", "Downloaded"),
                            ("undo", "Undid an operation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In progress"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("bytes_affected", models.BigIntegerField(default=0)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("reversible", models.BooleanField(default=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_from",
                        to="explorer.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_to",
                        to="explorer.node",
                    ),
                ),
                (
                    "undo_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undone_by",
                        to="explorer.operation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("size", models.BigIntegerField(default=0)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="explorer.node",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="explorer.operation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["trashed_at"], name="node_trashed_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                condition=models.Q(("starred", True)),
                fields=["starred"],
                name="node_starred_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["-modified_at"], name="node_recent_idx"),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                condition=models.Q(("trashed_at__isnull", True)),
                name="node_unique_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "file"),
                    models.Q(("kind", "folder"), ("size", 0)),
                    _connector="OR",
                ),
                name="node_folders_have_no_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="node_is_not_its_own_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["-created_at"], name="op_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["kind", "status"], name="op_kind_status_idx"),
        ),
        migrations.AddIndex(
            model_name="operationitem",
            index=models.Index(fields=["operation", "node"], name="opitem_op_node_idx"),
        ),
    ]
