# Generated by Django 6.1 on 2026-09-09 19:23

import django.core.files.storage
import django.db.models.deletion
import django.db.models.functions.text
import explorer.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/export"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("folder", "Folder"), ("file", "File")],
                        default="file",
                        max_length=6,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        default=0, help_text="Bytes. Always 0 for folders."
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=120)),
                (
                    "upload",
                    models.FileField(
                        blank=True, null=True, upload_to=explorer.models.upload_to
                    ),
                ),
                ("starred", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "path",
                    models.CharField(
                        db_index=True, default="", editable=False, max_length=1024
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("managed", "Created here"),
                            ("scanned", "Found on a share"),
                        ],
                        default="managed",
                        max_length=8,
                    ),
                ),
                (
                    "rel_path",
                    models.CharField(
                        blank=True,
                        help_text="POSIX path within the share.",
                        max_length=1024,
                    ),
                ),
                (
                    "fs_modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="mtime as reported by the share.",
                        null=True,
                    ),
                ),
                (
                    "missing_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when a scan no longer finds the file.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="explorer.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-kind", django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("create_folder", "Created folder"),
                            ("upload", "Added files"),
                            ("rename", "Renamed"),
                            ("move", "Moved"),
                            ("copy", "Copied"),
                            ("trash", "Moved to trash"),
                            ("restore", "Restored"),
                            ("purge", "Deleted permanently"),
                            ("star", "Starred"),
                            ("unstar", "Unstarred"),
                            ("download", "Downloaded"),
                            ("import", "Imported from share"),
                            ("transcode", "Converted"),
                            ("vanished", "Gone from share"),
                            ("undo", "Undid an operation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In progress"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("bytes_affected", models.BigIntegerField(default=0)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("reversible", models.BooleanField(default=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_from",
                        to="explorer.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_to",
                        to="explorer.node",
                    ),
                ),
                (
                    "undo_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undone_by",
                        to="explorer.operation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("size", models.BigIntegerField(default=0)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="explorer.node",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="explorer.operation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ScanRoot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120, unique=True)),
                (
                    "mount_path",
                    models.CharField(
                        help_text="Absolute path of the mounted share.", max_length=1024
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "read_only",
                    models.BooleanField(
                        default=True,
                        help_text="Refuse rename/move/delete on files catalogued from this share.",
                    ),
                ),
                (
                    "require_mount",
                    models.BooleanField(
                        default=True,
                        help_text="Abort unless mount_path is a real mount point.",
                    ),
                ),
                (
                    "max_missing_ratio",
                    models.FloatField(
                        default=0.25,
                        help_text="Abort the missing-file pass if a larger share of the catalogue vanished at once.",
                    ),
                ),
                ("follow_symlinks", models.BooleanField(default=False)),
                (
                    "max_depth",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 means unlimited."
                    ),
                ),
                (
                    "min_size",
                    models.BigIntegerField(
                        default=0, help_text="Skip files smaller than this."
                    ),
                ),
                (
                    "exclude",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="fnmatch patterns matched against each entry name.",
                    ),
                ),
                (
                    "missing_policy",
                    models.CharField(
                        choices=[
                            ("flag", "Flag as missing"),
                            ("trash", "Move to trash"),
                            ("delete", "Remove from the catalogue"),
                        ],
                        default="flag",
                        max_length=6,
                    ),
                ),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Entries per transaction. Keeps write locks short on long scans.",
                    ),
                ),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        help_text="Folder in the tree this share is mirrored into.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_roots",
                        to="explorer.node",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="node",
            name="scan_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nodes",
                to="explorer.scanroot",
            ),
        ),
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Scanning"),
                            ("done", "Finished"),
                            ("failed", "Failed"),
                            ("unavailable", "Share unavailable"),
                            ("aborted", "Stopped for safety"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("dry_run", models.BooleanField(default=False)),
                ("scanned", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("vanished", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("bytes_seen", models.BigIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                (
                    "problems",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="First few unreadable paths.",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_runs",
                        to="explorer.operation",
                    ),
                ),
                (
                    "scan_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="explorer.scanroot",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["-created_at"], name="op_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["kind", "status"], name="op_kind_status_idx"),
        ),
        migrations.AddIndex(
            model_name="operationitem",
            index=models.Index(fields=["operation", "node"], name="opitem_op_node_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["trashed_at"], name="node_trashed_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                condition=models.Q(("starred", True)),
                fields=["starred"],
                name="node_starred_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["-modified_at"], name="node_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["scan_root", "rel_path"], name="node_share_path_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                condition=models.Q(("trashed_at__isnull", True)),
                name="node_unique_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "file"),
                    models.Q(("kind", "folder"), ("size", 0)),
                    _connector="OR",
                ),
                name="node_folders_have_no_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="node_is_not_its_own_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scan_root__isnull", False)),
                fields=("scan_root", "rel_path"),
                name="node_unique_path_per_share",
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["scan_root", "-started_at"], name="scanrun_recent_idx"
            ),
        ),
    ]
